# -*- coding: utf-8 -*-
"""thaicons

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/Sasipimpiangbunta/9bc4ace54f5ae7cc1d8092785162e1c6/thaicons-py.ipynb
"""

import tkinter as tk
import random
import os

# Check if the environment has a display
if "DISPLAY" in os.environ:
    # List of Thai consonants and their names
    thai_consonants = [
        ("ก", "Gor Gai (ก ไก่)"),
        ("ข", "Khor Khai (ข ไข่)"),
        ("ค", "Khor Khuat (ค ขวด)"),
        ("ง", "Ngor Ngu (ง งู)"),
        ("จ", "Jor Jan (จ จาน)"),
        ("ช", "Chor Chang (ช ช้าง)"),
        ("ท", "Thor Thahan (ท ทหาร)"),
        ("น", "Nor Nu (น หนู)"),
        ("พ", "Phor Phan (พ พาน)"),
        ("ม", "Mor Ma (ม ม้า)"),
        ("ร", "Ror Rua (ร เรือ)"),
        ("ล", "Lor Ling (ล ลิง)"),
        ("ส", "Sor Suea (ส เสือ)"),
    ]

    class FlashcardGame:
        def __init__(self, root):
            self.root = root
            self.root.title("Thai Consonant Flashcard Game")

            self.current_card = None
            self.is_flipped = False

            self.card_frame = tk.Frame(root, width=300, height=200, bg="white", relief="raised", bd=5)
            self.card_frame.pack(pady=20)

            self.label = tk.Label(self.card_frame, text="", font=("Arial", 50), bg="white")
            self.label.pack(expand=True)

            self.card_frame.bind("<Button-1>", self.flip_card)
            self.label.bind("<Button-1>", self.flip_card)

            self.next_button = tk.Button(root, text="Next Card", command=self.next_card)
            self.next_button.pack(pady=10)

            self.next_card()

        def next_card(self):
            self.is_flipped = False
            self.current_card = random.choice(thai_consonants)
            self.label.config(text=self.current_card[0], font=("Arial", 100))

        def flip_card(self, event):
            if not self.is_flipped:
                self.label.config(text=self.current_card[1], font=("Arial", 20))
            else:
                self.label.config(text=self.current_card[0], font=("Arial", 100))
            self.is_flipped = not self.is_flipped

    if __name__ == "__main__":
        root = tk.Tk()
        game = FlashcardGame(root)
        root.mainloop()
else:
    # If there is no display, print a message
    print("No display found. GUI will not be shown.")